---
- hosts: webservers
  become: true
  vars_files:
    - vars.yml
  vars:
    foo: bar
    foo_list:
      - one
      - two
      - three

  pre_tasks:
     - name: "Pre Task"
       command: echo 'Beginning to updating ...'
       register: out
     - debug: var=out.stdout_lines

     - debug: msg="Variable 'foo' is set to {{ foo }}"

     - debug: msg="Variable 'foo_list[1]' is set to {{ foo_list[1] }}"

     - debug: msg="Variable from inventory, 'version' is set to {{ version }}"


     - name: Update apt cache if needed.
       apt: update_cache=yes cache_valid_time=3600

  post_tasks:
     - name: "Post Task"
       command: echo 'Done ...'
       register: out
     - debug: var=out.stdout_lines

  tasks:    
     - name: "Vars test"
       command: "ls -la {{ download_dir }}"
       register: out
     - debug: var=out.stdout_lines


     - name: "Vars test"
       command: "env"
       environment: download_dir
       register: out
     - debug: var=out.stdout_lines




